# 1 "/home/vdelacruz/Documents/Ethernet 2 Ports/module_ethernet_board_support/SOMANET-C22/check_slot.c"
# 1 "/home/vdelacruz/Documents/Ethernet 2 Ports/app_simple_webserver/.build_IPV4//"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/home/vdelacruz/Documents/Ethernet 2 Ports/module_ethernet_board_support/SOMANET-C22/check_slot.c"
